import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getAllContactedCreators } from "./tracking/outreach-log";

// Rebuilds INFLUENCERS.md from outreach-log.json every time this runs — a
// plain-text, non-code snapshot of everyone contacted so far, readable and
// editable without touching the JSON tracking file directly. Regenerated
// wholesale each run, so any hand edits to the file itself get overwritten
// next time — it's a read view onto the real data, not a second source of
// truth.

const OUTPUT_FILE = path.resolve("INFLUENCERS.md");

const PLATFORM_LABEL: Record<string, string> = {
  youtube: "YouTube",
  tiktok: "TikTok",
  instagram: "Instagram",
  other: "Other",
};

export function writeInfluencersMarkdown(): number {
  const creators = getAllContactedCreators();

  const lines: string[] = [];
  lines.push("# Influencers Contacted");
  lines.push("");
  lines.push(`_Auto-regenerated by \`npm run influencers-md\` — last built ${new Date().toISOString()}._`);
  lines.push("");
  lines.push(`Total contacted: ${creators.length}`);
  lines.push("");

  if (creators.length === 0) {
    lines.push("No real outreach sent yet.");
  } else {
    lines.push("| Creator | Platform | Niche | Status | Replied | Times Contacted | Last Contacted |");
    lines.push("|---|---|---|---|---|---|---|");
    for (const c of creators) {
      lines.push(
        `| ${c.channelName} | ${PLATFORM_LABEL[c.platform] ?? c.platform} | ${c.niche} | ${c.dealStatus} | ${
          c.replied ? "yes" : "no"
        } | ${c.timesContacted} | ${c.lastContactedAt.slice(0, 10)} |`,
      );
    }
  }

  lines.push("");
  fs.writeFileSync(OUTPUT_FILE, lines.join("\n") + "\n");
  return creators.length;
}

// Only actually runs the CLI entry point when invoked directly (`npm run
// influencers-md`) — importing writeInfluencersMarkdown from the web server
// must not also trigger this file's own top-level write. Compared via
// fileURLToPath rather than a raw string match against `file://${argv[1]}`
// — this project's own directory name has a space in it, which import.meta.url
// percent-encodes (%20) but argv[1] never does, so the naive string
// comparison silently never matched and this guard never fired.
if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const count = writeInfluencersMarkdown();
  console.log(`Wrote ${count} creator(s) to ${OUTPUT_FILE}`);
}
